### ISSUE TITLE
edge浏览器点贴子标题会打开新标签页

### ISSUE THREAD

**Issue by JINZHANG2017** [ccnnde/gzker-plus#1]
edge浏览器点贴子标题会打开新标签页，同时弹出贴子详情的框，今天突然出现的，之前都是只有弹出框不会打开新标签页，还有弹出框关不掉，只能关掉标签或者刷新

**Comment by JINZHANG2017** [comment]
![Uploading Snipaste_2024-07-17_16-23-50.png…]()

**Comment by JINZHANG2017** [comment]
![Snipaste_2024-07-17_16-23-50](https://github.com/user-attachments/assets/2414545f-e724-43ba-b403-55e0a3e0b6f9)

**Comment by ccnnde** [comment]
扩展选项里取消勾选“新标签页打开链接”中的 **主题** 选项可以解决

这块考虑不周，抱歉哈。因为之前新标签页打开时，**主题增强**功能是不生效的，新版本支持了这个功能

然后这个弹窗里的内容和主题页面自带的内容是重复的，所以对页面自带的内容做了隐藏处理，并且禁用了弹窗关闭，因为关闭后页面中间是空的

近期会更新下个版本，去掉遮罩层，避免误导

**Comment by JINZHANG2017** [comment]
好的多谢大佬

**Comment by ccnnde** [comment]
edge 已经更新了哈，兄弟可否 star 支持下
